/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./../src/components/Application/AppCard.vue')['default']
    ApplicationItem: typeof import('./../src/components/Application/ApplicationItem.vue')['default']
    ApplicationList: typeof import('./../src/components/Application/ApplicationList.vue')['default']
    BaseNavBar: typeof import('./../src/components/base/BaseNavBar.vue')['default']
    BasePage: typeof import('./../src/components/base/BasePage.vue')['default']
    CellItem: typeof import('./../src/components/Application/CellItem.vue')['default']
    CheckBadge: typeof import('./../src/components/Application/CheckBadge.vue')['default']
    CollapseItem: typeof import('./../src/components/Application/CollapseItem.vue')['default']
    FormItem: typeof import('./../src/components/base/FormItem.vue')['default']
    NavBar: typeof import('./../src/components/base/NavBar.vue')['default']
    NoData: typeof import('./../src/components/base/NoData.vue')['default']
    ScrollTop: typeof import('./../src/components/base/ScrollTop.vue')['default']
    Search: typeof import('./../src/components/Search/index.vue')['default']
    TabBar: typeof import('./../src/components/base/TabBar.vue')['default']
    Toast: typeof import('./../src/components/base/Toast.vue')['default']
    Upload: typeof import('./../src/components/base/Upload.vue')['default']
  }
}
