/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationItem: typeof import('./../src/components/Application/ApplicationItem.vue')['default']
    ApplicationList: typeof import('./../src/components/Application/ApplicationList.vue')['default']
    NavBar: typeof import('./../src/components/base/NavBar.vue')['default']
    NoData: typeof import('./../src/components/base/NoData.vue')['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ScrollTop: typeof import('./../src/components/base/ScrollTop.vue')['default']
    Search: typeof import('./../src/components/Search/index.vue')['default']
    TabBar: typeof import('./../src/components/base/TabBar.vue')['default']
    Toast: typeof import('./../src/components/base/Toast.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
  }
}
