/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./../src/components/base/NavBar.vue')['default']
    NoData: typeof import('./../src/components/base/NoData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('./../src/components/base/ScrollTop.vue')['default']
    TabBar: typeof import('./../src/components/base/TabBar.vue')['default']
    Toast: typeof import('./../src/components/base/Toast.vue')['default']
  }
}
